services:
  ikev2:
    image: ghcr.io/jmcat999/ikev2:latest
    pull_policy: always
    container_name: ikev2-mschapv2
    restart: unless-stopped
    network_mode: host
    privileged: true

    volumes:
      - /lib/modules:/lib/modules:ro
      - ./ssl:/ssl:ro
      - ./config/users.txt:/etc/ikev2/users.txt:ro

    env_file:
      - .env
