services:
  ikev2:
    image: ghcr.io/jmcat999/ikev2:latest
    container_name: ikev2-mschapv2
    restart: unless-stopped
    network_mode: host
    privileged: true

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    volumes:
      - /lib/modules:/lib/modules:ro
      - ./certs:/certs:ro

    env_file:
      - .env
